apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fmct
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-fmct@sha256:d32696ee9704cae2f3cad485db8c40a803081cb0e1940a251510f2c64ccbaf83
        name: my-nodejs
        resources: {}
status: {}
